name: 'This is my first action package by isaacbats'
description: 'Greet someone and record the time for my first personal action'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: '🤖'
  color: 'blue'
